name = "svelte-cloudflare"
compatibility_date = "2023-06-28"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = "./svelte-kit/cloudflare"

kv_namespaces = [
  { binding = "AUTH_STORAGE", id = "09d660bda1a64539a745578e20a69091" }
]

